name: AquaRealmCommands
version: '${project.version}'
main: me.tj.aquarealmcommands.AquaRealmCommands
api-version: '1.20'
commands:
  gmc:
    description: Gamemode Creative
    usage: /gmc or /gmc <player>

  gms:
    description: Gamemode Survival
    usage: /gms or /gms <player>

  gmsp:
    description: Gamemode Spectator
    usage: /gmsp or /gmsp <player>

  msg:
    description: Msg people.
    usage: /msg <player> <message>

  r:
    description: Reply to people that sent you a message
    usage: /r <message>